#!/usr/bin/env php
<?php

require file_exists(__DIR__ . '/vendor/autoload.php')
    ? __DIR__ . '/vendor/autoload.php'
    : __DIR__ . '/../../autoload.php';

$appVersion = '1.0.0-DEV';

$app = new Symfony\Component\Console\Application('DroidPHP Command', $appVersion);
$app->add(new Droidphp\Command\AboutCommand($appVersion));
$app->add(new Droidphp\Command\BuildCommand());
$app->add(new Droidphp\Command\SetupCommand());
$app->setDefaultCommand('about');
$app->run();